<nav class="navbar navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
  <a class="navbar-brand" href="#">
    <img src="img/form_logo.png" width="30" height="30" class="d-inline-block align-top" alt="">
    App Help Desk
  </a>
</nav>

<div class="container p-4">
  <div class="row">
    <div class="col">

      <form method="post" action="/autenticar">
        <div class="mb-3">
          <label  class="form-label">Email</label>
          <input type="email" class="form-control" name="email">
        </div>
        <div class="mb-3">
          <label for="exampleInputPassword1" class="form-label">Senha</label>
          <input type="password" class="form-control"  name="senha">
        </div>
        <div class="mb-3 form-check">
          <input type="checkbox" class="form-check-input" id="exampleCheck1">
          <label class="form-check-label" for="exampleCheck1">Check me out</label>
        </div>
        <button type="submit" class="btn btn-primary">Entrar</button>
        <?php
        if ($this->view->login == 'erro') { ?>
          <span class="text text-danger">email ou senha incorretos contate o administrador</span>
        <?php } ?>
      </form>
    </div>
  </div>
</div>