<div class="container justifi-content-center" style="padding-top: 120px;">
  <div>
    <div class="col-6 offset-3">
      <div class="card">
        <div class="card-header">
          LOGIN
        </div>
        <div class="card-body">
          <form action="/autenticar" method="post">
            <div class="mb-3">
              <label for="exampleInputEmail1" class="form-label">Email</label>
              <input type="email" class="form-control" aria-describedby="emailHelp" name="email" placeholder="Digite seu endereço de e-mail ...">
              <div id="emailHelp" class="form-text">Não compartilharemos seu e-mail com ninguem.</div>
            </div>
            <div class="mb-3">
              <label class="form-label">Senha</label>
              <input type="Password" class="form-control" name="senha" placeholder="Digite sua senha ....">
            </div>
            <button type="submit" class="btn btn-primary btn-lg" style="float: right;">Entrar</button>
          </form>
        </div>
      </div>
      <? if ($this->view->login == 'erro') { ?>
        <div class="alert alert-danger alert-dismissible fade show" role="alert" style="margin-top: 10px;">
          <strong>Erro !!! </strong> Valide o seu e-mail e senha.
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
      <? } ?>
    </div>
  </div>
</div>