<div class="container bg-light card" style="margin-top: 40px;">
  <div class="row align-items-center">
    <div class="col card-body">
      <form method="post" action="/autenticar">
        <div class="">

        </div>
        <div class="mb-3">
          <label for="exampleInputEmail1" class="form-label">Email address</label>
          <input name="email" type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
        </div>
        <div class="mb-3">
          <label for="exampleInputPassword1" class="form-label">Password</label>
          <input name="senha" type="password" class="form-control" id="exampleInputPassword1">
        </div>
        <div class="mb-3 ">
          <?php
          if ($this->view->login == 'erro') { ?>
            <span class="alert alert-danger form-text form-control"><strong>Erro login: </strong> <?
              if ($this->view->login == 'erro') { ?>
                <span class="text text-danger">email ou senha incorretos contate o administrador</span>
              <?php } ?></span>
          <? } ?>
                  <button type="submit" class="btn btn-primary btn-lg" style="float: right;">Entrar</button>
        </div>

      </form>
    </div>
  </div>
</div>