<div class="container p-4">
  <div class="row">
    <div class="col">
      <div class="card">
        <div class="card-header"> Adicionar Usuario</div>
        <div class="card-body">
          <form action='/salvarChamado' method="POST">
            <div class="form-group">
              <label>Título</label>
              <input type="text" name="titulo" class="form-control" placeholder="Título">
            </div>

            <div class="form-group">
              <label>Categoria</label>
              <select class="form-control" name="categoria">
                <option>Criação Usuário</option>
                <option>Impressora</option>
                <option>Hardware</option>
                <option>Software</option>
                <option>Rede</option>
              </select>
            </div>

            <div class="form-group">
              <label>Descrição</label>
              <textarea class="form-control" name="descricao" rows="3"></textarea>
            </div>

            <div class="row mt-5" style="float: right;">
              <div class="col-6">
                <button class="btn btn-success btn-block" type="submit">Enviar</button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>