<div class="container p-4">
  <div class="row">
    <div class="col">
      <div class="card">
        <div class="card-header"> Criar um novo Chamado</div>
        <div class="card-body">
          <form action='/inserirChamado' method="POST">
            <div class="form-group">
              <label>Categoria</label>
              <select class="form-control" name="categoria">
                <option>Criação Usuário</option>
                <option>Impressora</option>
                <option>Hardware</option>
                <option>Software</option>
                <option>Rede</option>
              </select>
            </div>

            <div class="form-group ">
              <label>Descrição</label>
              <textarea class="form-control" name="descricao" rows="3"></textarea>
            </div>
            <div class="p-4">
              <a type="submit" href="/homepage" class="btn btn-primary">Voltar</a>
              <button class="btn btn-success btn-block" type="submit" style="float: right;">Enviar</button>
            </div>
        </div>
        </form>
      </div>
    </div>
  </div>
</div>
</div>