
    <div class="container p-4">
        <div class="row">
            <div class="col">
                <div class="card">
                    <div class="card-header"> Adicionar Usuario</div>
                    <div class="card-body">
                        <form method="post" action="/salvarUsuario">
                            <div class="mb-3">
                                <label class="form-label">Email</label>
                                <input type="email" class="form-control" name="email">
                            </div>
                            <div class="mb-3">
                                <label for="exampleInputPassword1" class="form-label">Senha</label>
                                <input type="password" class="form-control" name="senha">
                            </div>
                            <div class="mb-3 form-check">
                                <input type="checkbox" class="form-check-input" id="exampleCheck1">
                                <label class="form-check-label" for="exampleCheck1">Check me out</label>
                            </div>
                            <button type="submit" class="btn btn-primary">Entrar</button>
                            <? if ($this->view->login == 'erro') { ?>
                                <span class="text text-danger">email ou senha incorretos contate o administrador</span>
                            <?php } ?>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>