<nav class="navbar navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="/homepage">Help Desk</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Adicionar
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="/addUsuario">Usuario</a></li>
            <li><a class="dropdown-item" href="/addChamado">Chamados</a></li>
            <li>
              <hr class="dropdown-divider">
            </li>
            <li><a class="dropdown-item" href="#">Usuarios</a></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

<? if (isset($_GET['Usuario_salvo'])) { ?>
  <div class="alert alert-success alert-dismissible fade show" role="alert">
    <strong>Usuario</strong> cadastrado com sucesso
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<? } ?>

<? if (isset($_GET['Usuario_removido'])) { ?>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <strong>Usuario</strong> removido com sucesso
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<? } ?>

<? if (isset($_GET['Chamado_salvo'])) { ?>
  <div class="alert alert-success alert-dismissible fade show" role="alert">
    <strong>Chamado</strong> salvo com sucesso
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<? } ?>

<? if (isset($_GET['Chamado_removido'])) { ?>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <strong>Chamado</strong> removido com sucesso
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<? } ?>


<? if (!empty($this->view->chamados)) { ?>
  <div class="container mt-3">
    <div class="row alert alert-primary">
      <div class="col">
        <strong>Chamados</strong>
      </div>

      <div class="col">
        <input class="form-control" type="search" aria-label="Search" />
      </div>

      <div class="col d-flex align-items-end">
        <button class="btn btn-success" type="submit">Buscar</button>
      </div>

    </div>
    <table class="table">
      <thead>
        <tr>
          <th scope="col">Ticket</th>
          <th scope="col">Solicitante</th>
          <th scope="col">Categoria</th>
          <th scope="col">Ação</th>
        </tr>
      </thead>
      <tbody>
        <? foreach ($this->view->chamados as  $chamado) { ?>
          <tr>
            <th scope="row"><a data-bs-toggle="modal" data-bs-target="#editarChamado<?= $chamado['id'] ?>" type="button"><?= 'A00' . $chamado['id'] ?></a></th>
            <td><?= $chamado['nome'] ?></td>
            <td><?= $chamado['categoria'] ?></td>
            <td><a href="/excluirChamado?id=<?= $chamado['id'] ?>" class="btn btn-danger">Excluir</a></td>
          </tr>

          <!-- Modal para edição de chamado -->
          <div class="modal fade" id="editarChamado<?= $chamado['id'] ?>" tabindex="-1"
            aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-xl">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title">A00<?= $chamado['id'] ?></h5>
                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                  <form action='/editarChamado' method="POST">
                    <input type="hidden" name="id" value="<?= $chamado['id'] ?>">
                    <div class="mb-3">
                      <label class="form-label">Usuario</label>
                      <input type="text" name="titulo" class="form-control" value="<?= $chamado['nome'] ?>" disabled>
                    </div>
                    <div class="mb-3">
                      <label class="form-label">Categoria</label>
                      <select class="form-control" name="categoria">
                        <option>Criação Usuário</option>
                        <option>Impressora</option>
                        <option>Hardware</option>
                        <option>Software</option>
                        <option>Rede</option>
                      </select>
                    </div>

                    <div class="mb-3">
                      <label class="form-label">Descrição</label>
                      <textarea class="form-control" name="descricao" rows="3"><?= $chamado['descricao'] ?></textarea>
                    </div>
                    <div class="p-4">
                      <button class="btn btn-success btn-block" type="submit" style="float: right;">Alterar</button>
                    </div>
                </div>
                </form>
              </div>
            </div>
          </div>
        <? } ?>
      </tbody>
    </table>
  </div>



<? } ?>