<nav class="navbar navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Help Desk</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Adicionar
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="/addUsuario">Usuario</a></li>
            <li><a class="dropdown-item" href="/addChamado">Chamados</a></li>
            <li>
              <hr class="dropdown-divider">
            </li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" aria-label="Search" />
        <button class="btn btn-success" type="submit">Buscar</button>
      </form>
    </div>
  </div>
</nav>
<? if (isset($this->view->Usuario_salvo) && $this->view->Usuario_salvo) { ?>
  <div class="alert alert-success alert-dismissible fade show" role="alert">
    <strong>Usuario</strong> cadastrado com sucesso
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<? } ?>

<? if (isset($this->view->Chamado_salvo) && $this->view->Chamado_salvo) { ?>
  <div class="alert alert-success alert-dismissible fade show" role="alert">
    <strong>Chamado</strong> aberto com sucesso
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<? } ?>



<div class="row p-4">
  <div class="col">
    <div class="alert alert-primary" role="alert">
      <strong>Chamados</strong>
    </div>
    <table class="table">
      <thead>
        <tr>
          <th scope="col">ID</th>
          <th scope="col">Solicitante</th>
          <th scope="col">Titulo</th>
          <th scope="col">Categoria</th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <? foreach ($this->view->chamados as $id_chamado => $chamado) { ?>
          <tr>
            <th scope="row"><?= $chamado['id'] ?></th>
            <td><?= $chamado['nome'] ?></td>
            <td><?= $chamado['titulo'] ?></td>
            <td><?= $chamado['categoria'] ?></td>
            <td><a href="/excluirChamado?id=<?=$chamado['id']?>" class="btn btn-danger">Excluir</a></td>
            <td><a href="/editar?<?=$chamado['id']?>" class="btn btn-success">Editar</a></td>
          </tr>
        <? } ?>
      </tbody>
    </table>
  </div>
</div>

<div class="row p-4">
  <div class="col">
    <div class="alert alert-primary" role="alert">
      <strong>Usuarios</strong>
    </div>
    <table class="table">
      <thead>
        <tr>
          <th scope="col">ID</th>
          <th scope="col">Nome</th>
          <th scope="col">Email</th>
          <th scope="col">Nivel</th>
        </tr>
      </thead>
      <tbody>
        <? foreach ($this->view->usuarios as $id_usuario => $usuario) { ?>
          <tr>
            <th scope="row"><?= $chamado['id'] ?></th>
            <td><?= $usuario['nome'] ?></td>
            <td><?= $usuario['email'] ?></td>
            <td>definir</td>
          </tr>
        <? } ?>
      </tbody>
    </table>
  </div>
</div>